title: "Crown Creatives v2"
description: "Clean rebuild of the Crown Creatives website."

baseurl: "/crown-creatives-v2"
url: "https://pmr76.github.io"

markdown: kramdown

version: 5

include:
  - _pages

plugins:
  - jekyll-feed
  - jekyll-seo-tag
